version: '3'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
  envoy-discovery:
    image: sample-envoy-proxy/envoy-discovery:1.1-SNAPSHOT
    ports:
      - "8080"
    links:
      - zipkin
    environment:
      SERVER_PORT: 8080
  envoy:
    image: envoyproxy/envoy:dev
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.json:/etc/envoy/envoy.json
    depends_on:
      - envoy-discovery
    links:
      - envoy-discovery
  person-service:
    image: sample-envoy-proxy/person-service:1.1-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      - envoy-discovery
    links:
      - zipkin
      - envoy-discovery
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://envoy-discovery:8080
  product-service:
    image: sample-envoy-proxy/product-service:1.1-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      - envoy-discovery
    links:
      - zipkin
      - envoy-discovery
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://envoy-discovery:8080